### ISSUE TITLE
Include speedup percentage and allocated memory reduction in performance tables

### ISSUE THREAD

**Issue by JustinWick** [krauthaufen/MapNew#3]
This is an impressive performance achievement, especially for such a core data structure. Relative performance for this implementation would be much easier to assess if the percentage of speedup (by mean times), and memory reduction was presented as part of the table.

**Comment by krauthaufen** [comment]
Hey, I actually did that [here](https://aardvarkians.com/demo/MapNew/#OfSeq) but I'll update the readme too
